#pragma once
// GENERATED by generate_waveform_tree_header.py; no retraining.
// Float64 custom Tree producer train_waveform_14features.py, commit 4859fa6.
// Leaf counts reconstructed from the matched training waveforms, all 23 node counts and majority labels verified.
static const unsigned TINGGU_MODEL_FEATURE_COUNT=14, TINGGU_MODEL_CLASS_COUNT=3;
static const char TINGGU_MODEL_VERSION[]="waveform_tree14_20260913_verified_20260915";
static const char TINGGU_MODEL_SHA256[]="931739fd3b9687146fa5e0afbb47f1089017bd24cc5315091fb27e8ee40f8dda";
static const double TINGGU_MODEL_CONFIDENCE_THRESHOLD=0.50;
struct TingguTreeNode {int feature,left,right,prediction;double threshold;unsigned counts[3];};
static const TingguTreeNode TINGGU_TREE_NODES[]={
  {6,1,10,0,8.0884407780514103,{116,85,88}},
  {2,2,7,0,144.10493489528511,{115,8,1}},
  {8,3,4,0,47.769012244433554,{16,6,1}},
  {-1,-1,-1,0,0,{16,0,0}},
  {0,5,6,1,677,{0,6,1}},
  {-1,-1,-1,1,0,{0,4,0}},
  {-1,-1,-1,1,0,{0,2,1}},
  {6,8,9,0,7.0794523989039533,{99,2,0}},
  {-1,-1,-1,0,0,{98,0,0}},
  {-1,-1,-1,1,0,{1,2,0}},
  {9,11,16,2,1.1344875970794575,{1,77,87}},
  {7,12,13,1,251.95898622647732,{0,61,5}},
  {-1,-1,-1,1,0,{0,54,0}},
  {0,14,15,1,999.5,{0,7,5}},
  {-1,-1,-1,1,0,{0,6,0}},
  {-1,-1,-1,2,0,{0,1,5}},
  {3,17,20,2,53.174879696448357,{1,16,82}},
  {11,18,19,2,13.185599437897977,{1,14,23}},
  {-1,-1,-1,2,0,{1,1,14}},
  {-1,-1,-1,1,0,{0,13,9}},
  {12,21,22,2,20.396985597376862,{0,2,59}},
  {-1,-1,-1,2,0,{0,2,6}},
  {-1,-1,-1,2,0,{0,0,53}}
};
static const char* const TINGGU_FEATURE_NAMES[]={"peak_abs","peak_time_ms","rms_0_100ms","rms_100_300ms","dominant_freq_hz","spectral_centroid_hz","low_high_energy_ratio","decay_tau_ms","piezo_std","accel_mag_mean","accel_mag_std","gyro_mag_mean","gyro_mag_std","mpu_valid_ratio"};
