"""Recover leaf counts only after every exported population matches; never fit a tree."""
from pathlib import Path
import argparse, json, hashlib
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser()
p.add_argument('--features',type=Path,default=ROOT/'tmp/tree_verification/producer_features.csv')
p.add_argument('--model',type=Path,default=ROOT/'models/20260913/decision_tree_full.json')
p.add_argument('--output',type=Path,default=ROOT/'firmware/tinggu_edge_runtime/tree_model_parameters.h')
a=p.parse_args();model=json.loads(a.model.read_text());data=pd.read_csv(a.features);names=model['feature_names'];labels=['tight','medium','loose'];nodes=[]
x=data[names].to_numpy(dtype=float);y=data.label.map(dict(zip(labels,range(3)))).to_numpy()
assert np.isfinite(x).all() and not pd.isna(y).any()
def visit(n,indices):
 i=len(nodes);nodes.append(None);counts=np.bincount(y[indices].astype(int),minlength=3)
 assert len(indices)==n['n'], (i,len(indices),n['n'])
 assert int(np.argmax(counts))==n['pred'], (i,counts,n['pred'])
 if 'j' in n:
  mask=x[indices,n['j']]<=n['thr'];left=visit(n['left'],indices[mask]);right=visit(n['right'],indices[~mask]);j=n['j'];t=n['thr']
 else: left=right=-1;j=-1;t=0.0
 nodes[i]=(j,left,right,n['pred'],t,counts.tolist())
 return i
visit(model['root'],np.arange(len(x)))
s='#pragma once\n// GENERATED by generate_waveform_tree_header.py; no retraining.\n'
s+='// Float64 custom Tree producer train_waveform_14features.py, commit 4859fa6.\n'
s+='// Leaf counts reconstructed from the matched training waveforms, all 23 node counts and majority labels verified.\n'
s+='static const unsigned TINGGU_MODEL_FEATURE_COUNT=14, TINGGU_MODEL_CLASS_COUNT=3;\n'
s+='static const char TINGGU_MODEL_VERSION[]="waveform_tree14_20260913_verified_20260915";\n'
s+='static const char TINGGU_MODEL_SHA256[]="'+hashlib.sha256(a.model.read_bytes()).hexdigest()+'";\n'
s+='static const double TINGGU_MODEL_CONFIDENCE_THRESHOLD=0.50;\n'
s+='struct TingguTreeNode {int feature,left,right,prediction;double threshold;unsigned counts[3];};\n'
s+='static const TingguTreeNode TINGGU_TREE_NODES[]={\n'
s+=',\n'.join('  {%d,%d,%d,%d,%.17g,{%d,%d,%d}}'%(*n[:5],*n[5]) for n in nodes)+'\n};\n'
s+='static const char* const TINGGU_FEATURE_NAMES[]={'+','.join(json.dumps(n) for n in names)+'};\n'
a.output.write_text(s,encoding='utf-8');print('Verified and exported',len(nodes),'nodes,',len(x),'training rows')
